name: "asr_model"
backend: "python"
max_batch_size: 1

input [
  {
    name: "audio_path"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

output [
  {
    name: "transcription"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

instance_group [
  {
    count: 5
    kind: KIND_GPU
  }
]

dynamic_batching {
  max_queue_delay_microseconds: 100000
  preserve_ordering: False
}