version: '3.8'

services:
  triton-server:
    build:
      context: ./triton-service/
      dockerfile: Dockerfile
    image: triton:latest
    container_name: triton
  

    # GPU configuration
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    # Shared memory and limits
    shm_size: '32gb'
    ulimits:
      memlock: -1
      stack: 67108864

    # Port mappings
    ports:
      - "2000:2000"  # HTTP
      - "2001:2001"  # gRPC
      - "2002:2002"  # Metrics

    # Volume mappings
    volumes:
      - ./triton-service/model_repository:/models
      - model-cache:/.cache
      - /home/sj/Desktop/data/back2/bytepulse-ai/s2a-omar-development/triton_analysis/audio_temp_folder:/data/uploads:ro
      - /tmp/s2a:/tmp/s2a:ro

    # Restart policy
    restart: unless-stopped

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2000/v2/health/ready"]
      interval: 300s
      timeout: 10s
      retries: 5
      start_period: 300s

volumes:
  model-cache:
    driver: local

networks:
  default:
    name: triton-server