version: '3.8'

services:
  asr-triton-server:
    build:
      context: ./triton-service/asr_triton  # Replace with your first Dockerfile's folder path
      dockerfile: Dockerfile
    container_name: asr-triton-server
    ports:
      - "4000:4000"  # HTTP
      - "4001:4001"  # gRPC
      - "4002:4002"  # Metrics
    volumes:
      - ./triton-service/asr_triton/models:/models  # Mount your models directory
      - /home/sj/Desktop/data/back2/bytepulse-ai/s2a-omar-development/triton_analysis/audio_temp_folder:/data/uploads:ro
      - /tmp/s2a:/tmp/s2a:ro
    environment:
      - CUDA_VISIBLE_DEVICES=0  # Adjust GPU allocation as needed
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1  # Adjust based on your GPU availability
              capabilities: [gpu]
    # Shared memory and limits
    shm_size: '32gb'
    ulimits:
      memlock: -1
      stack: 67108864
    restart: unless-stopped
    networks:
      - triton-network

  diarization-triton-server:
    build:
      context: ./triton-service/diarization_triton  # Replace with your second Dockerfile's folder path
      dockerfile: Dockerfile
    container_name: diarization-triton-server
    ports:
      - "5000:5000"  # HTTP
      - "5001:5001"  # gRPC
      - "5002:5002"  # Metrics
    volumes:
      - ./triton-service/diarization_triton/models:/models  # Mount your models directory
    environment:
      - CUDA_VISIBLE_DEVICES=0  # Adjust GPU allocation as needed
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1  # Adjust based on your GPU availability
              capabilities: [gpu]
    # Shared memory and limits
    shm_size: '32gb'
    ulimits:
      memlock: -1
      stack: 67108864
    restart: unless-stopped
    networks:
      - triton-network

  mistral-triton-server:
    build:
      context: ./triton-service/mistral_triton  # Replace with your third Dockerfile's folder path
      dockerfile: Dockerfile
    container_name: mistral-triton-server
    ports:
      - "6000:6000"  # HTTP
      - "6001:6001"  # gRPC
      - "6002:6002"  # Metrics
    volumes:
      - ./triton-service/mistral_triton/models:/models  # Mount your models directory
    environment:
      - CUDA_VISIBLE_DEVICES=0  # Adjust GPU allocation as needed
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1  # Adjust based on your GPU availability
              capabilities: [gpu]

    # Shared memory and limits
    shm_size: '32gb'
    ulimits:
      memlock: -1
      stack: 67108864
    restart: unless-stopped
    networks:
      - triton-network

networks:
  triton-network:
    driver: bridge
