# Base image
FROM nvcr.io/nvidia/tritonserver:25.10-trtllm-python-py3

RUN pip install nemo_toolkit['all']

# Expose ports
EXPOSE 3600 3601 3602

# Set working directory
WORKDIR /models

# Start Triton server
CMD ["tritonserver", \
     "--model-repository=/models", \
     "--log-verbose=1", \
     "--log-info=true", \
     "--log-warning=true", \
     "--log-error=true", \
     "--exit-on-error=false", \
     "--http-port=3600", \
     "--grpc-port=3601", \
     "--metrics-port=3602", \
     "--allow-http=true", \
     "--allow-grpc=true", \
     "--allow-metrics=true", \
     "--strict-readiness=false"]
