# Base image
FROM nvcr.io/nvidia/tritonserver:25.10-trtllm-python-py3

# Expose ports
EXPOSE 3700 3701 3702

# Set working directory
WORKDIR /models

# Start Triton server
CMD ["tritonserver", \
     "--model-repository=/models", \
     "--log-verbose=1", \
     "--log-info=true", \
     "--log-warning=true", \
     "--log-error=true", \
     "--exit-on-error=false", \
     "--http-port=3700", \
     "--grpc-port=3701", \
     "--metrics-port=3702", \
     "--allow-http=true", \
     "--allow-grpc=true", \
     "--allow-metrics=true", \
     "--strict-readiness=false"]