# Base image
FROM nvcr.io/nvidia/tritonserver:25.10-trtllm-python-py3


COPY ./requirements-triton.txt requirements.txt
# Install required Python packages
RUN pip install -r requirements.txt

# Create necessary directories
RUN mkdir -p /models /.cache

# Expose ports
EXPOSE 2000 2001 2002

# Set working directory
WORKDIR /models

# Start Triton server
CMD ["tritonserver", \
     "--model-repository=/models", \
     "--log-verbose=1", \
     "--log-info=true", \
     "--log-warning=true", \
     "--log-error=true", \
     "--exit-on-error=false", \
     "--http-port=2000", \
     "--grpc-port=2001", \
     "--metrics-port=2002", \
     "--allow-http=true", \
     "--allow-grpc=true", \
     "--allow-metrics=true", \
     "--strict-readiness=false"]